// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQB5Yo5QHFriuJ8PmGJj62ih6wO5PRHxY',
    appId: '1:22097784366:web:dd24369d92c6f2f491f9bf',
    messagingSenderId: '22097784366',
    projectId: 'book-store-d2826',
    authDomain: 'book-store-d2826.firebaseapp.com',
    storageBucket: 'book-store-d2826.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_MR-j46olSVNOVD3sshn5Ouok2dEvDfo',
    appId: '1:22097784366:android:e9ab22b32919e8d491f9bf',
    messagingSenderId: '22097784366',
    projectId: 'book-store-d2826',
    storageBucket: 'book-store-d2826.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCnZpxDoyHuk71z6iaAcZRbSdrfGz1TQ',
    appId: '1:22097784366:ios:7ae97b0a9a56bed191f9bf',
    messagingSenderId: '22097784366',
    projectId: 'book-store-d2826',
    storageBucket: 'book-store-d2826.firebasestorage.app',
    iosClientId: '22097784366-lm15ee80p39r7390t3n8q2uu5kjdihm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCnZpxDoyHuk71z6iaAcZRbSdrfGz1TQ',
    appId: '1:22097784366:ios:7ae97b0a9a56bed191f9bf',
    messagingSenderId: '22097784366',
    projectId: 'book-store-d2826',
    storageBucket: 'book-store-d2826.firebasestorage.app',
    iosClientId: '22097784366-lm15ee80p39r7390t3n8q2uu5kjdihm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQB5Yo5QHFriuJ8PmGJj62ih6wO5PRHxY',
    appId: '1:22097784366:web:2c836ee35ef0041791f9bf',
    messagingSenderId: '22097784366',
    projectId: 'book-store-d2826',
    authDomain: 'book-store-d2826.firebaseapp.com',
    storageBucket: 'book-store-d2826.firebasestorage.app',
  );

}